const firstWeek = [
    {
        id: 1,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "13:00",
                status: false,
                passed: false,
                note: "",
                date: "21-06-2021",
            },
        ],
        totalTasks: 1,
        date: "21-06-2021",
        day: "Monday",
    },
    {
        id: 2,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "08:00",
                status: false,
                passed: false,
                note: "",
                date: "22-06-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "09:00",
                status: true,
                passed: false,
                note: "",
                date: "22-06-2021",
            },
        ],
        totalTasks: 2,
        date: "22-06-2021",
        day: "Thursday",
    },
    {
        id: 3,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "18:00",
                status: false,
                passed: false,
                note: "",
                date: "23-06-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "19:00",
                status: true,
                passed: false,
                note: "",
                date: "23-06-2021",
            },
        ],
        totalTasks: 2,
        date: "23-06-2021",
        day: "Wednesday",
    },
    {
        id: 4,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "24-06-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "05:00",
                status: true,
                passed: false,
                note: "",
                date: "24-06-2021",
            },
            {
                id: 3,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "24-06-2021",
            },
        ],
        totalTasks: 3,
        date: "24-06-2021",
        day: "Thursday",
    },
    {
        id: 5,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "14:00",
                status: false,
                passed: false,
                note: "",
                date: "25-06-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "25-06-2021",
            },
        ],
        totalTasks: 2,
        date: "25-06-2021",
        day: "Friday",
    },
    {
        id: 6,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "26-06-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "26-06-2021",
            },
        ],
        totalTasks: 2,
        date: "26-06-2021",
        day: "Saturday",
    },
    {
        id: 7,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "27-06-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "05:00",
                status: true,
                passed: false,
                note: "",
                date: "27-06-2021",
            },
            {
                id: 3,
                name: "Test",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "27-06-2021",
            },
            {
                id: 4,
                name: "Bernard",
                time: "19:00",
                status: true,
                passed: false,
                note: "",
                date: "27-06-2021",
            },
        ],
        totalTasks: 4,
        date: "27-06-2021",
        day: "Sunday",
    },
];

const secondWeek = [
    {
        id: 1,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "13:00",
                status: false,
                passed: false,
                note: "",
                date: "28-06-2021",
            },
        ],
        totalTasks: 1,
        date: "28-06-2021",
        day: "Monday",
    },
    {
        id: 2,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "08:00",
                status: false,
                passed: false,
                note: "",
                date: "29-06-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "09:00",
                status: true,
                passed: false,
                note: "",
                date: "29-06-2021",
            },
            {
                id: 3,
                name: "Walk the dog",
                time: "19:00",
                status: true,
                passed: false,
                note: "",
                date: "29-06-2021",
            },
        ],
        totalTasks: 3,
        date: "29-06-2021",
        day: "Thursday",
    },
    {
        id: 3,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "18:00",
                status: false,
                passed: false,
                note: "",
                date: "30-06-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "19:00",
                status: true,
                passed: false,
                note: "",
                date: "30-06-2021",
            },
            {
                id: 3,
                name: "Walk the dog",
                time: "09:00",
                status: true,
                passed: false,
                note: "",
                date: "30-06-2021",
            },
        ],
        totalTasks: 3,
        date: "30-06-2021",
        day: "Wednesday",
    },
    {
        id: 4,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "01-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "05:00",
                status: true,
                passed: false,
                note: "",
                date: "01-07-2021",
            },
            {
                id: 3,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "01-07-2021",
            },
            {
                id: 4,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "01-07-2021",
            },
            {
                id: 5,
                name: "Walk the dog",
                time: "23:00",
                status: true,
                passed: false,
                note: "",
                date: "01-07-2021",
            },
        ],
        totalTasks: 5,
        date: "01-07-2021",
        day: "Thursday",
    },
    {
        id: 5,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "14:00",
                status: false,
                passed: false,
                note: "",
                date: "02-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "02-07-2021",
            },
            {
                id: 3,
                name: "Walk the dog",
                time: "22:00",
                status: true,
                passed: false,
                note: "",
                date: "02-07-2021",
            },
            {
                id: 4,
                name: "Walk the dog",
                time: "02:00",
                status: true,
                passed: false,
                note: "",
                date: "02-07-2021",
            },
        ],
        totalTasks: 4,
        date: "02-07-2021",
        day: "Friday",
    },
    {
        id: 6,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "03-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "03-07-2021",
            },
            {
                id: 3,
                name: "Walk the dog",
                time: "12:00",
                status: true,
                passed: false,
                note: "",
                date: "03-07-2021",
            },
            {
                id: 4,
                name: "Do the Dishes",
                time: "05:00",
                status: true,
                passed: false,
                note: "",
                date: "03-07-2021",
            },
        ],
        totalTasks: 4,
        date: "03-07-2021",
        day: "Saturday",
    },
    {
        id: 7,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "04-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "05:00",
                status: true,
                passed: false,
                note: "",
                date: "04-07-2021",
            },
            {
                id: 3,
                name: "Test",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "04-07-2021",
            },
            {
                id: 4,
                name: "Bernard",
                time: "19:00",
                status: true,
                passed: false,
                note: "",
                date: "04-07-2021",
            },
            {
                id: 5,
                name: "Bernard",
                time: "11:00",
                status: true,
                passed: false,
                note: "",
                date: "04-07-2021",
            },
            {
                id: 6,
                name: "Bernard",
                time: "09:00",
                status: true,
                passed: false,
                note: "",
                date: "04-07-2021",
            },
        ],
        totalTasks: 6,
        date: "04-07-2021",
        day: "Sunday",
    },
];

const thirdWeek = [
    {
        id: 1,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "13:00",
                status: false,
                passed: false,
                note: "",
                date: "05-07-2021",
            },
        ],
        totalTasks: 1,
        date: "05-07-2021",
        day: "Monday",
    },
    {
        id: 2,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "08:00",
                status: false,
                passed: false,
                note: "",
                date: "06-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "09:00",
                status: true,
                passed: false,
                note: "",
                date: "06-07-2021",
            },
        ],
        totalTasks: 2,
        date: "06-07-2021",
        day: "Thursday",
    },
    {
        id: 3,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "18:00",
                status: false,
                passed: false,
                date: "07-07-2021",
                note: "",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "19:00",
                status: true,
                passed: false,
                note: "",
                date: "07-07-2021",
            },
        ],
        totalTasks: 2,
        date: "07-07-2021",
        day: "Wednesday",
    },
    {
        id: 4,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "08-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "05:00",
                status: true,
                passed: false,
                note: "",
                date: "08-07-2021",
            },
            {
                id: 3,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "08-07-2021",
            },
            {
                id: 4,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "08-07-2021",
            },
            {
                id: 5,
                name: "Walk the dog",
                time: "23:00",
                status: true,
                passed: false,
                note: "",
                date: "08-07-2021",
            },
        ],
        totalTasks: 5,
        date: "08-07-2021",
        day: "Thursday",
    },
    {
        id: 5,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "14:00",
                status: false,
                passed: false,
                note: "",
                date: "09-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "09-07-2021",
            },
            {
                id: 3,
                name: "Walk the dog",
                time: "22:00",
                status: true,
                passed: false,
                note: "",
                date: "09-07-2021",
            },
            {
                id: 4,
                name: "Walk the dog",
                time: "02:00",
                status: true,
                passed: false,
                note: "",
                date: "09-07-2021",
            },
        ],
        totalTasks: 4,
        date: "09-07-2021",
        day: "Friday",
    },
    {
        id: 6,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "10-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "10-07-2021",
            },
            {
                id: 3,
                name: "Walk the dog",
                time: "12:00",
                status: true,
                passed: false,
                note: "",
                date: "10-07-2021",
            },
        ],
        totalTasks: 3,
        date: "10-07-2021",
        day: "Saturday",
    },
    {
        id: 7,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "11-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "05:00",
                status: true,
                passed: false,
                note: "",
                date: "11-07-2021",
            },
            {
                id: 3,
                name: "Test",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "11-07-2021",
            },
            {
                id: 4,
                name: "Bernard",
                time: "19:00",
                status: true,
                passed: false,
                note: "",
                date: "11-07-2021",
            },
            {
                id: 5,
                name: "Bernard",
                time: "11:00",
                status: true,
                passed: false,
                note: "",
                date: "11-07-2021",
            },
        ],
        totalTasks: 5,
        date: "11-07-2021",
        day: "Sunday",
    },
];

const fourthWeek = [
    {
        id: 1,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "13:00",
                status: false,
                passed: false,
                note: "",
                date: "12-07-2021",
            },
        ],
        totalTasks: 1,
        date: "12-07-2021",
        day: "Monday",
    },
    {
        id: 2,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "08:00",
                status: false,
                passed: false,
                note: "",
                date: "13-07-2021",
            },
        ],
        totalTasks: 1,
        date: "13-07-2021",
        day: "Thursday",
    },
    {
        id: 3,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "18:00",
                status: false,
                passed: false,
                note: "",
                date: "14-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "19:00",
                status: true,
                passed: false,
                note: "",
                date: "14-07-2021",
            },
        ],
        totalTasks: 2,
        date: "14-07-2021",
        day: "Wednesday",
    },
    {
        id: 4,
        tasks: [],
        totalTasks: 0,
        date: "15-07-2021",
        day: "Thursday",
    },
    {
        id: 5,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "14:00",
                status: false,
                passed: false,
                note: "",
                date: "16-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "16-07-2021",
            },
        ],
        totalTasks: 2,
        date: "16-07-2021",
        day: "Friday",
    },
    {
        id: 6,
        tasks: [],
        totalTasks: 0,
        date: "17-07-2021",
        day: "Saturday",
    },
    {
        id: 7,
        tasks: [
            {
                id: 1,
                name: "Do the Dishes",
                time: "04:00",
                status: false,
                passed: false,
                note: "",
                date: "18-07-2021",
            },
            {
                id: 2,
                name: "Walk the dog",
                time: "05:00",
                status: true,
                passed: false,
                note: "",
                date: "18-07-2021",
            },
            {
                id: 3,
                name: "Test",
                time: "15:00",
                status: true,
                passed: false,
                note: "",
                date: "18-07-2021",
            },
            {
                id: 4,
                name: "Bernard",
                time: "19:00",
                status: true,
                passed: false,
                note: "",
                date: "18-07-2021",
            },
        ],
        totalTasks: 4,
        date: "18-07-2021",
        day: "Sunday",
    },
];

const notificationsList = [
    {
        id: 1,
        content: "Go to the dentist",
        task: {
            id: 1,
            time: "15:00",
            date: "27-06-2021",
            status: true,
        },
        done: true,
    },
    {
        id: 2,
        content: "Bernard",
        task: {
            id: 1,
            time: "19:00",
            date: "28-06-2021",
            status: true,
        },
        done: true,
    },
    {
        id: 3,
        content: "Do the Dishes",
        task: {
            id: 1,
            time: "04:00",
            date: "24-06-2021",
            status: false,
        },
        done: false,
    },
    {
        id: 4,
        content: "Do the Dishes",
        task: {
            id: 1,
            time: "05:00",
            date: "23-06-2021",
            status: false,
        },
        done: false,
    },
    {
        id: 5,
        content: "Do the Dishes",
        task: {
            id: 1,
            time: "05:00",
            date: "23-06-2021",
            status: false,
        },
        done: false,
    },
    {
        id: 6,
        content: "Do the Dishes",
        task: {
            id: 1,
            time: "05:00",
            date: "23-06-2021",
            status: false,
        },
        done: false,
    },
    {
        id: 7,
        content: "Go to the dentist",
        task: {
            id: 1,
            time: "15:00",
            date: "27-06-2021",
            status: true,
        },
        done: true,
    },
    {
        id: 8,
        content: "Go to Chen",
        task: {
            id: 1,
            time: "19:00",
            date: "27-06-2021",
            status: false,
        },
        done: true,
    },
];
